In [1]:
import numpy as np           
# kisi bhi codefile ko import karaya jasakta hy e.g:"import math as mt "."import mubashir as mb"
#mt.sum() us file k functions call ho sakty hain phir
#from mubashir import sum,add,anyfunction inside   

In [16]:
list1 = [1,2]*2
list1

[1, 2, 1, 2]

In [17]:
a1 = np.array([1,2,3,4,5])

In [18]:
a1

array([1, 2, 3, 4, 5])

In [19]:
a1+a1+a1

array([ 3,  6,  9, 12, 15])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
a1*2

array([ 2,  4,  6,  8, 10])

In [22]:
a1*a1

array([ 1,  4,  9, 16, 25])

In [23]:
a1 = a1*a1

In [24]:
a1

array([ 1,  4,  9, 16, 25])

In [27]:
%timeit a2 = np.arange(1000)


2.92 µs ± 46.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
dim_0 = np.array(5)

In [29]:
dim_0.ndim 

0

In [30]:
dim_2 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])

In [31]:
dim_2.ndim

2

In [32]:
dim_3 = np.array([[[11,2,3,4],[5,6,7,8]],[[5,6,7,8],[1,2,3,4]]])

In [33]:
dim_3.ndim

3

In [34]:
type(a1)

numpy.ndarray

In [35]:
np.size(dim_3)

16

In [36]:
a3 = np.array([0]*10)

In [37]:
#convert a pythone range to numpy array
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.ones(16).reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
z = np.arange(120).reshape(10,12)
print(z*5)

[[  0   5  10  15  20  25  30  35  40  45  50  55]
 [ 60  65  70  75  80  85  90  95 100 105 110 115]
 [120 125 130 135 140 145 150 155 160 165 170 175]
 [180 185 190 195 200 205 210 215 220 225 230 235]
 [240 245 250 255 260 265 270 275 280 285 290 295]
 [300 305 310 315 320 325 330 335 340 345 350 355]
 [360 365 370 375 380 385 390 395 400 405 410 415]
 [420 425 430 435 440 445 450 455 460 465 470 475]
 [480 485 490 495 500 505 510 515 520 525 530 535]
 [540 545 550 555 560 565 570 575 580 585 590 595]]


In [62]:
np.ones(10).reshape(2,6)  #cannot reshape array of size 10 into shape (2,6)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [68]:
#evenly spaced #'s between two intervals    
#equidistance
np.linspace(0,50,17)

array([ 0.   ,  3.125,  6.25 ,  9.375, 12.5  , 15.625, 18.75 , 21.875,
       25.   , 28.125, 31.25 , 34.375, 37.5  , 40.625, 43.75 , 46.875,
       50.   ])

In [80]:
d2 = np.array([[1,2,3,4,5,6,7,8,9,0],[11,22,33,44,55,66,77,88,99,00]])

In [81]:
d2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0],
       [11, 22, 33, 44, 55, 66, 77, 88, 99,  0]])

In [82]:
#index se value pick karlo
d2[1,4]

55

In [108]:
w = np.random.randint(50)

In [109]:
w

3

In [110]:
w = np.random.randn(12).reshape(3,4)

In [111]:
w

array([[ 1.95988874,  1.23800758, -0.07035944, -1.15925061],
       [-2.92977451,  0.46161555, -0.92305491, -0.45819873],
       [ 0.1424767 ,  0.85064382,  0.7172478 , -0.52935979]])

In [112]:
w[1:2,2:3]#jitni dimensional array hogi slicing me utni hi dimensions use karni hongi

array([[-0.92305491]])

In [116]:
w[1,2]

-0.9230549062081569

In [117]:
w[1,2] > 0 

False

In [6]:
my_list = [1,2,3]
type(my_list)

list

In [7]:
import numpy as np

In [8]:
data = np.array(my_list)
data 

In [10]:
type(data) #  data type of array

numpy.ndarray

In [12]:
data.dtype # data type of elements

dtype('int32')

In [16]:
x = np.array([2,3,True,"hello"])   # dtype='<U11' numpy ki data type
x

array(['2', '3', 'True', 'hello'], dtype='<U11')

In [18]:
data_2 = np.array([[1,2,3],[2,3,4]]) # always put multiple list in a higher list
data_2

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
data_2.ndim

2

dimension humy ye batati hain k isky axis kitny hain e.g: x,y,z etc 

In [21]:
data_2.shape # shape humy rows and coloumns batati hain

(2, 3)

In [22]:
newlist = [1,2,3]
oldlist = [4,5,6]
newlist+oldlist

[1, 2, 3, 4, 5, 6]

In [23]:
np_new_list = np.array(newlist)
np_old_list = np.array(oldlist)
print(np_new_list)
print(np_old_list)

[1 2 3]
[4 5 6]


In [26]:
np_new_list+np_old_list #elementvise addition for list (not concatinat)

array([5, 7, 9])

In [27]:
np_new_list-np_old_list #elementvise subtraction for list

array([-3, -3, -3])

In [28]:
np_new_list/np_old_list#elementvise division for list

array([0.25, 0.4 , 0.5 ])

In [29]:
np_new_list*np_old_list#elementvise multiplication for list

array([ 4, 10, 18])

In [31]:
np_new_list%np_old_list#elementvise modulusfor list

array([1, 2, 3], dtype=int32)

In [35]:
x = list(range(10)) # range k function se list nahi banti   # convert klarni parti hy

In [34]:
data_3 = np.arange(10) # series creat kata hy list nahi
data_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
data_3*2 #multiply

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
scaler = np.array(5)
print(scaler)
print(type(scaler))
print(scaler.ndim)# no dimension for array
print(scaler.shape) #no rows &colomn

5
<class 'numpy.ndarray'>
0
()


In [41]:
scaler = np.array([5])
print(scaler)
print(type(scaler))
print(scaler.ndim)
print(scaler.shape)

[5]
<class 'numpy.ndarray'>
1
(1,)


In [43]:
data_3**5 #elementvise power function

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049], dtype=int32)

In [76]:
data = np.random.randn(2,3) #shape di gai hain random array k liey
data

array([[-0.04798896, -0.48965239, -0.80470088],
       [-0.28961044,  0.91193789, -0.75998954]])

In [77]:
data.dtype

dtype('float64')

In [78]:
data.astype(np.int64) #intiger me convert karna hy

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [79]:
data.dtype=int

In [91]:
data_ki_type = np.array([1.5,7.4,3.1,4.2],dtype=int)

In [92]:
data_ki_type.dtype = float
data_ki_type

array([1.48539705e-313, 8.48798317e-314])

In [96]:
data_5 = np.arange(20).reshape(4,5) 
data_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [97]:
data_5.shape

(4, 5)

In [104]:
data_6 = np.arange(1,76).reshape(3,25)

In [105]:
data_6

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75]])

In [106]:
data_6.reshape(25,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48],
       [49, 50, 51],
       [52, 53, 54],
       [55, 56, 57],
       [58, 59, 60],
       [61, 62, 63],
       [64, 65, 66],
       [67, 68, 69],
       [70, 71, 72],
       [73, 74, 75]])

In [109]:
data_7 = np.zeros(10).reshape(5,2)
data_7

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [111]:
data_8 = np.zeros((5,2))
data_8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [123]:
data_9=np.zeros((5,5))
data_9

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [127]:
data_10 = np.empty((2,3,2))
data_10

array([[[1.52812108e-312, 0.00000000e+000],
        [3.62633684e+228, 3.98450716e+252],
        [2.42772983e+198, 9.34634029e+218]],

       [[1.47250772e-052, 3.98477332e+252],
        [1.47278599e+179, 9.08367237e+223],
        [1.16466228e-028, 2.57799344e-312]]])

In [10]:
index_array = np.arange(36).reshape((9,4))
index_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [11]:
print(index_array[2])   # indexing k return me scaler value ati hy 
print(index_array[1,2])

[ 8  9 10 11]
6


In [12]:
index_array[-1,2]

34

In [13]:
print(index_array[1:3,0:2]) # slicing left side pr rows slice hongy or right side pr coloumns

[[4 5]
 [8 9]]


In [14]:
data_14d = np.array([[[[[[[[[[[[[[50]]]]]]]]]]]]]]) # jitni bracket utny dimensions

In [15]:
data_14d.ndim

14

In [16]:
data_14d.shape # it shows axis

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [17]:
dim_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(dim_3) # [depth,rows,coloumns]
dim_3.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [18]:
block = np.arange(9).reshape((3,3)) #slicing

In [19]:
block

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
block[:2,1:]

array([[1, 2],
       [4, 5]])

In [22]:
block[2:,:]

array([[6, 7, 8]])

In [ ]:
#tranposing matrix

In [23]:
arr = np.arange(15).reshape((3, 5))

In [24]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr.T #transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [26]:
np.dot(arr.T, arr) #dot product

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [27]:
arr = np.arange(16).reshape((2, 2, 4))

In [28]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [29]:
arr.transpose((1, 0, 2))  #3d transposing

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [30]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [32]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [34]:
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [35]:
np.exp(arr)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]]])

In [36]:
x = np.random.randn(8)

In [39]:
x

array([ 1.0995153 ,  1.39760326, -0.87500788, -0.04271643,  1.38847334,
        0.38784874,  0.61670939, -0.34950084])

In [37]:
y = np.random.randn(8)

In [40]:
y

array([ 0.24969192, -0.92302564,  0.23723924,  1.4321142 , -0.48097429,
       -0.90606302,  0.19649849, -0.5036652 ])

In [38]:
np.maximum(x, y)

array([ 1.0995153 ,  1.39760326,  0.23723924,  1.4321142 ,  1.38847334,
        0.38784874,  0.61670939, -0.34950084])

In [41]:
np.ones((5,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [42]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [54]:
arr = np.arange(20).reshape(5,4)

In [55]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
arr[[0,3,4]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [57]:
arr[[-3,-4]]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [58]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
arr[[1,2,3,2],[0,3,1,2]]

array([ 4, 11, 13, 10])

In [60]:
arr.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [67]:
arr = np.array([[1,2,3],[4,5,6]])

In [68]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [73]:
arr_uniq = np.array([1,2,7,3,6,1,4,9])

In [74]:
np.unique(arr_uniq)

array([1, 2, 3, 4, 6, 7, 9])

In [75]:
x=[1,2,2,2,3]

In [78]:
set(x)

{1, 2, 3}

In [79]:
arr = np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [86]:
x = arr.ravel()
x[0]=14     #' ravel karny k baad orignal me bhi changing hogi copy k sath'
x

array([14,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
arr

array([[14,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [89]:
y=arr.flatten()
y[0] =4
y

array([ 4,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
arr

array([[14,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [92]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [95]:
print(arr1,"\n-----------------\n",arr2)

[[1 2 3]
 [4 5 6]] 
-----------------
 [[ 7  8  9]
 [10 11 12]]


In [99]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [100]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [102]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

numpy importents for tests
python for data analysis ch4


In [5]:
a=np.arange(20).reshape(4,5)

In [6]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
b = np.zeros_like(a)

In [8]:
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
c= np.ones_like(a)

In [10]:
c

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
a.dtype

dtype('int32')

In [12]:
a.astype(np.int64)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int64)

In [13]:
a.dtype

dtype('int32')