In [2]:
import numpy as np  # np is allies

In [122]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [123]:
to_square = range(100000)

In [124]:
%timeit squares(to_square)

11.2 ms ± 527 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [120]:
array_to_square = np.arange(0, 100000)

In [126]:
%timeit array_to_square ** 2

37.6 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
a1 = np.array([1, 2, 3, 4, 5])

In [35]:
a1

array([1, 2, 3, 4, 5])

In [36]:
a1+a1+a1

array([ 3,  6,  9, 12, 15])

In [37]:
np.arange(1,10,2).ndim

1

In [38]:
dim_0 = np.array(5)

In [33]:
dim_0.ndim

0

In [39]:
dim_2 = np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
dim_2.ndim

2

In [45]:
dim_3= np.array([[[1,2,3],[4,5,6],[7,9,8]]])

In [46]:
a = np.array([[[[[[[[[[[[[5]]]]]]]]]]]]])

In [47]:
a.ndim

13

In [48]:
np.size(a)

1

In [49]:
# any float in the sequences makes
# it an array of floats
a2 = np.array([1, 2, 3, 4.0, 5.0])
a2

array([1., 2., 3., 4., 5.])

In [4]:
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
[4]*5

[4, 4, 4, 4, 4]

In [52]:
# convert a python range to numpy array
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
z= np.ones(120).reshape(10,12)
print(z*5)


[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [75]:
np.size(z,1)

12

In [67]:
#The np.linspace() function is similar to np.arange() , but generates an array of a
#specific number of items between the specified start and stop values:

# evenly spaced #'s between two intervals
np.linspace(1, 50, 10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [79]:
d2 = np.array([[1,2,3,4,5,6,7,8,9,0],[11,22,33,44,55,66,77,88,99,00]])

In [81]:
d2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0],
       [11, 22, 33, 44, 55, 66, 77, 88, 99,  0]])

In [82]:
d2[1,4]

55

In [111]:
w = np.random.randn(12).reshape(4,3)

In [115]:
w

array([[-2.23349832, -0.65478858,  0.73256524],
       [ 1.33912694,  1.40419405,  0.54720011],
       [ 0.14383491, -0.19128825,  0.11131575],
       [-1.38740612, -1.85573316, -1.7164888 ]])

In [114]:
w[1:2, 2:]

array([[0.54720011]])

In [116]:
w[1,2]

0.5472001079323153

In [4]:
a = range(2,9)
map(lambda x, y: x ** y, a, reversed(a))

In [5]:
print(105+89)

194


In [6]:
77+65

142

In [7]:
96-57

39

In [8]:
print(np.power(np.array([1,2,3]),4))

[ 1 16 81]


In [9]:
print(np.negative(np.array([1,2,3])))

[-1 -2 -3]


In [10]:
print(np.exp(np.array([1,2,3])))

[ 2.71828183  7.3890561  20.08553692]


In [11]:
print(np.log(np.array([1,2,3])))

[0.         0.69314718 1.09861229]


In [5]:
print(np.sin(np.array([1,2,3])))

[0.84147098 0.90929743 0.14112001]


In [23]:

arr = np.random.randn(15).reshape(3,5)
arr

AttributeError: 'numpy.ndarray' object has no attribute 'seed'

In [9]:
arr.shape

(3, 5)

In [11]:
arr.ndim

2

In [18]:
np.ceil(arr)

array([[ 2.,  1.,  2., -1., -0.],
       [ 1.,  2., -1., -0., -0.],
       [ 1., -2., -0.,  1.,  2.]])

In [14]:
arr1

array([[ True,  True,  True, False, False],
       [ True,  True, False, False, False],
       [ True, False, False,  True,  True]])